name: blue_print_pos
description: Plugin to connecting bluetooth printer device, support on Android and iOS
version: 0.0.16
homepage: https://github.com/andriyoganp/blue_print_pos

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  # Handler bluetooth for Android
  blue_thermal_printer:
    git:
      url: https://github.com/zloykurd/blue_thermal_printer.git
      ref: master
  # Utilities for generate ByteBuffer
  esc_pos_utils_plus: ^2.0.4
  # Framework
  flutter:
    sdk: flutter
  # Handler bluetooth for iOS
  flutter_blue_plus: ^1.35.5
  # Image utilities
  image: ^4.5.4
  # Generate qr image painter
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: kg.zkdev.blue_print_pos
        pluginClass: BluePrintPosPlugin
      ios:
        pluginClass: BluePrintPosPlugin
