plugins {
    id "com.android.application"
    id "kotlin-android"
}

android {
    compileSdk = flutter.compileSdkVersion
    namespace "kg.zkdev.blue_print_pos"
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "kg.zkdev.blue_print_pos"
        minSdkVersion 24
        targetSdkVersion 35
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }
}

flutter {
    source '../..'
}

dependencies {
}
